#!/usr/bin/env bash

while getopts ":p:" flag; do
    case $flag in
    p)
        PORT=$OPTARG
    ;;
    esac
done

if [ "$PORT" = "" ]; then

    echo "-p flag is required"
    exit 1

fi

for file in *.py; do
    ampy -p $PORT put $file
done
